spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: changelog-master.xml
  jpa:
    defer-datasource-initialization: false
  main:
    lazy-initialization: true